default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: twitgram_base
  username: twit_user
  password: 111
  host: localhost

test:
  <<: *default
  database: mysite_test

production:
  <<: *default
  database: twitgram_base
  username: twit_user
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
