default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: twit_user
  password: your_password
  host: localhost

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: twitgram_base
  username: twit_user
  password: <%= ENV["MYAPP_DATABASE_PASSWORD"] %>
  host: dpg-cksfk8p0at9c73d9e4cg-a
  port: 5432