databases:
  - name: twitgram_base
    databaseName: twitgram_base
    user: twit_user

services:
  - type: web
    name: Twitgram
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: twitgram_base
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false